export const homeStyles = {
    container: "flex flex-col",
    heroSection: "relative bg-secondary/20 overflow-hidden",
    heroContent: "container mx-auto grid md:grid-cols-2 gap-12 items-center py-20 md:py-32 relative z-10 pointer-events-none",
    heroTextWrapper: "z-10 pointer-events-auto md:bg-transparent bg-background/40 md:backdrop-blur-none backdrop-blur-md md:p-0 p-6 rounded-lg md:border-0 border border-white/20",
    heroTitle: "text-4xl font-extrabold tracking-tight text-foreground md:text-6xl drop-shadow-md",
    heroDescription: "mt-6 max-w-2xl text-lg text-foreground/80",
    heroButtons: "mt-8 flex flex-col sm:flex-row gap-4",
    emergencyButton: "bg-background/80 backdrop-blur-sm",
    heroImageWrapper: "absolute inset-0 h-full w-full z-0 translate-x-0 md:translate-x-1/4",
    heroImage: "object-cover w-full h-full",
    heroGradient: "absolute inset-0 bg-gradient-to-t from-background via-background/50 to-transparent md:bg-gradient-to-l md:from-background md:via-background/50 md:to-transparent",

    departmentsSection: "py-20 bg-background",
    departmentsContainer: "container mx-auto",
    sectionTitle: "mb-12 text-center text-3xl font-bold",
    departmentsGrid: "grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6",

    whyChooseUsSection: "py-20 bg-muted/50",
    whyChooseUsContainer: "container mx-auto",
    whyChooseUsGrid: "grid gap-8 md:grid-cols-2 lg:grid-cols-3",
    featureCard: "p-6",
    featureContent: "flex flex-col items-start gap-4",
    featureIconWrapper: "flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary",
    featureIcon: "h-6 w-6",
    featureTitle: "text-lg font-bold",
    featureDescription: "mt-1 text-muted-foreground",

    statsSection: "py-16 bg-secondary text-secondary-foreground",
    statsContainer: "container mx-auto",
    statsGrid: "grid grid-cols-2 gap-8 text-center md:grid-cols-4",
    statItem: "rounded-lg p-4 transition-transform hover:scale-105",
    statValue: "text-4xl font-extrabold tracking-tighter",
    statLabel: "mt-2 text-sm uppercase tracking-wider text-primary-foreground/80",

    testimonialsSection: "py-20 bg-background",
    testimonialsContainer: "container mx-auto",
    carousel: "w-full",
    carouselItem: "md:basis-1/2 lg:basis-1/3",
    testimonialWrapper: "p-1 h-full",
    testimonialCard: "flex flex-col justify-between h-full shadow-lg hover:shadow-primary/10 transition-shadow duration-300 border-l-4 border-primary",
    testimonialContent: "pt-6",
    starsWrapper: "flex mb-2",
    starIcon: "h-5 w-5 text-yellow-400 fill-current",
    quote: "italic text-muted-foreground",
    avatar: "h-12 w-12",
    testimonialName: "text-base font-bold",
    carouselPrev: "ml-12",
    carouselNext: "mr-12",

    ctaSection: "py-20 bg-primary/90 text-primary-foreground",
    ctaContainer: "container mx-auto text-center",
    ctaTitle: "text-3xl font-bold",
    ctaDescription: "mt-4 max-w-2xl mx-auto",
    ctaButtonWrapper: "mt-8",
    ctaButton: "bg-background text-primary hover:bg-background/90 transform transition-transform hover:scale-105"
};
