export const homeStyles = {
    container: "flex flex-col",
    heroSection: "relative bg-gradient-to-br from-blue-50 to-white dark:from-slate-900 dark:to-slate-800 overflow-hidden",
    heroContent: "container mx-auto grid md:grid-cols-2 gap-8 lg:gap-12 items-center py-8 md:py-16 relative z-10",
    heroTextWrapper: "flex flex-col gap-6 text-center md:text-left z-20",
    heroTitle: "text-4xl font-extrabold tracking-tight text-slate-900 dark:text-white md:text-5xl lg:text-6xl drop-shadow-sm leading-tight",
    heroDescription: "text-lg text-slate-600 dark:text-slate-300 md:text-xl leading-relaxed max-w-2xl mx-auto md:mx-0",
    heroButtons: "mt-4 flex flex-col sm:flex-row gap-4 justify-center md:justify-start",
    emergencyButton: "bg-white/80 backdrop-blur-sm hover:bg-white shadow-sm text-red-600 border-red-100 ring-1 ring-red-50",
    heroImageContainer: "relative z-10 px-4 md:px-0 mt-8 md:mt-0",
    heroImageWrapper: "relative rounded-2xl md:rounded-[2rem] overflow-hidden shadow-2xl border-4 border-white dark:border-slate-700 bg-white ring-1 ring-slate-100",
    heroImage: "object-cover w-full h-auto",
    heroDecoration: "absolute -z-10 bg-primary/5 rounded-full blur-3xl",

    departmentsSection: "py-20 bg-background",
    departmentsContainer: "container mx-auto",
    sectionTitle: "mb-12 text-center text-3xl font-bold",
    departmentsGrid: "grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-6",

    whyChooseUsSection: "py-20 bg-muted/50",
    whyChooseUsContainer: "container mx-auto",
    whyChooseUsGrid: "grid gap-8 md:grid-cols-2 lg:grid-cols-3",
    featureCard: "p-6",
    featureContent: "flex flex-col items-start gap-4",
    featureIconWrapper: "flex h-12 w-12 flex-shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary",
    featureIcon: "h-6 w-6",
    featureTitle: "text-lg font-bold",
    featureDescription: "mt-1 text-muted-foreground",

    statsSection: "py-16 bg-secondary text-secondary-foreground",
    statsContainer: "container mx-auto",
    statsGrid: "grid grid-cols-2 gap-8 text-center md:grid-cols-4",
    statItem: "rounded-lg p-4 transition-transform hover:scale-105",
    statValue: "text-4xl font-extrabold tracking-tighter",
    statLabel: "mt-2 text-sm uppercase tracking-wider text-primary-foreground/80",

    testimonialsSection: "py-20 bg-background",
    testimonialsContainer: "container mx-auto",
    carousel: "w-full",
    carouselItem: "md:basis-1/2 lg:basis-1/3",
    testimonialWrapper: "p-1 h-full",
    testimonialCard: "flex flex-col justify-between h-full shadow-lg hover:shadow-primary/10 transition-shadow duration-300 border-l-4 border-primary",
    testimonialContent: "pt-6",
    starsWrapper: "flex mb-2",
    starIcon: "h-5 w-5 text-yellow-400 fill-current",
    quote: "italic text-muted-foreground",
    avatar: "h-12 w-12",
    testimonialName: "text-base font-bold",
    carouselPrev: "ml-12",
    carouselNext: "mr-12",

    ctaSection: "py-20 bg-primary/90 text-primary-foreground",
    ctaContainer: "container mx-auto text-center",
    ctaTitle: "text-3xl font-bold",
    ctaDescription: "mt-4 max-w-2xl mx-auto",
    ctaButtonWrapper: "mt-8",
    ctaButton: "bg-background text-primary hover:bg-background/90 transform transition-transform hover:scale-105"
};
